### ISSUE TITLE
Doesn't ask to Authorize 

### ISSUE THREAD

**Issue by Luminary-Five** [tgraupmann/ChromaDiscordApp#1]
Upon running the app and selecting connect to discord events, it doesn't ask for authorization.

**Comment by At0micA55** [comment]
Same for me \!/ i can't seem to find the fix for it... i'l contact Discord...

**Comment by mwalden2004** [comment]
Same here

**Comment by jriggz** [comment]
I'll jump in. I think it asked to authorize once, but nothing happened. I've never been able to force it to ask to authorize again and it's not listed in Discord's "Authorized Apps" tab.

**Comment by mwalden2004** [comment]
Sounds like an unmaintained repo, probably should be reported to Razer to be removed from there list of applications in Chroma.

**Comment by markdangerchen** [comment]
Same issue here... Just bought the razer headset stand so that I could get led notifications for discord and slack only to discover after installing it that both discord and slack are no longer working with chroma.  :(

**Comment by tgraupmann** [comment]
This was a scope issue with RPC. This issue has been fixed.
