### ISSUE TITLE
Authorize screen won't pop up

### ISSUE THREAD

**Issue by glvidrine8** [tgraupmann/ChromaDiscordApp#11]
Title says it all, I click "connect to discord events" button and it does nothing

**Comment by msolano90** [comment]
Also experiencing this issue on ChromaDiscordApp-1.0.1.0 and Discord release Stable 65694 (8a0ab1f)

**Comment by AutoUnder** [comment]
Mine is doing the same too, it also isn't working at all with my Razer Nommo Chroma speakers either

**Comment by AutoUnder** [comment]
It's working with Razer Nommo now but still won't authorize

**Comment by lazer27** [comment]
Same here Razer Blackwidow Chroma keyboard

**Comment by hanters** [comment]
Guys, pls take the latest version:
https://github.com/tgraupmann/ChromaDiscordApp/releases/tag/1.0.11

**Comment by mathias-bevers** [comment]
This will only work if you have the latest version. On the home page, he links to an older version. You can always find the latest version on [this](https://github.com/tgraupmann/ChromaDiscordApp/releases) page.

**Comment by tgraupmann** [comment]
This is something that has since been fixed. I reduced the scope and the auth popup works again.
