### ISSUE TITLE
Only working sometimes / somewhat

### ISSUE THREAD

**Issue by jazamatazz** [tgraupmann/ChromaDiscordApp#17]
I have the app installed and set to run at startup, authorized it, turned it on, and put it above Visualizer on the Chroma Apps segment of the Synapse app... but it only works sometimes. When I don't have the Discord app focused it turns green when I get a message, for instance, but if I get a message when I'm in Discord it doesn't work. Is it supposed to do that? Also nothing happens when I join or leave a voice channel. And it won't let me customize what the animations are, even when I uncheck "Connect to Discord Events," everything stays greyed out.
Thanks!

**Comment by tgraupmann** [comment]
One thing I added to the documentation is I realized your Discord status has to be online to get the message events.
