### ISSUE TITLE
App is confused about being authorized

### ISSUE THREAD

**Issue by hanskokx** [tgraupmann/ChromaDiscordApp#19]
- Version 1.0.13
- Discord Stable 88863 (957df89)
- Windows 10 64-Bit (10.0.19043)

Despite being authorized and able to receive events, I am unable to customize anything.

![image](https://user-images.githubusercontent.com/1911919/123552425-13828180-d744-11eb-9ad5-e7d24ae100ae.png)

**Comment by nodiaque** [comment]
Same here, and did the reauthorize many things.

**Comment by tgraupmann** [comment]
This was an RPC scope issue that has since been fixed.

**Comment by Hypnos2137** [comment]
But it is not fixed. I tried to reauthorize many times. But it sill doesn't show up in authorized apps in discord.

**Comment by tgraupmann** [comment]
Make sure you are on the latest version.
https://github.com/tgraupmann/ChromaDiscordApp/releases/tag/1.0.16

**Comment by Hypnos2137** [comment]
Clean reinstall did the trick,. Thanks.
