### ISSUE TITLE
Link to "Releases Chroma Discord App (Unofficial) Installer for Windows" points to version 1.0!

### ISSUE THREAD

**Issue by cwm9cwm9** [tgraupmann/ChromaDiscordApp#20]
If you go to the main tgraupmann/ChromaDiscordApp page at https://github.com/tgraupmann/ChromaDiscordApp

Scroll to Releases

The link "Chroma Discord App (Unofficial) Installer for Windows" takes you to https://github.com/tgraupmann/ChromaDiscordApp/releases/tag/1.0 when it should take you to https://github.com/tgraupmann/ChromaDiscordApp/releases

Simply delete the "/tag/1.0" part

**Comment by tgraupmann** [comment]
Thanks for the heads up. Fixed the link!
