### ISSUE TITLE
malwarebytes backdoor

### ISSUE THREAD

**Issue by Mintboi88** [tgraupmann/ChromaDiscordApp#21]
![Screenshot 2023-03-27 035008](https://user-images.githubusercontent.com/69445294/228014714-875eeb9d-4447-4158-b99e-192182cd1f00.png)
![Screenshot 2023-03-27 035035](https://user-images.githubusercontent.com/69445294/228014719-3daa56e2-0cdc-4110-b629-42534440af5c.png)
Malwarebytes

[www.malwarebytes.com](https://www.malwarebytes.com/)

-Log Details-

Scan Date: 3/27/23

Scan Time: 3:45 AM

Log File: 582b0dfe-cc73-11ed-a105-d8bbc1b32e18.json

-Software Information-

Version: [4.5.24.248](https://4.5.24.248/)

Components Version: 1.0.1952

Update Package Version: 1.0.67206

License: Trial

-System Information-

OS: Windows 10 (Build 19045.2728)

CPU: x64

File System: NTFS

User: MSI\Mint

-Scan Summary-

Scan Type: Threat Scan

Scan Initiated By: Manual

Result: Completed

Objects Scanned: 344871

Threats Detected: 1

Threats Quarantined: 0

Time Elapsed: 3 min, 11 sec

-Scan Options-

Memory: Enabled

Startup: Enabled

Filesystem: Enabled

Archives: Enabled

Rootkits: Enabled

Heuristics: Enabled

PUP: Detect

PUM: Detect

-Scan Details-

Process: 0

(No malicious items detected)

Module: 0

(No malicious items detected)

Registry Key: 0

(No malicious items detected)

Registry Value: 0

(No malicious items detected)

Registry Data: 0

(No malicious items detected)

Data Stream: 0

(No malicious items detected)

Folder: 0

(No malicious items detected)

File: 1

Backdoor.Agent.Generic, C:\USERS\xxxxx\APPDATA\ROAMING\MICROSOFT\WINDOWS\START MENU\PROGRAMS\STARTUP\CHROMADISCORDAPP.URL, No Action By User, 5396, 664490, 1.0.67206, , ame, , 91D57E832947C6D0E63547CC44374A55, 7CA3F7ADFF7FCE09E850891D30A389477ED2DEA274239783B748BBF8D2CF6D85

Physical Sector: 0

(No malicious items detected)

WMI: 0

(No malicious items detected)

(end)

**Comment by tgraupmann** [comment]
This has to be a false positive. You can look at the contents of the shortcut.

```
C:\Users\YOUR_USER_NAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup>type ChromaDiscordApp.url
[InternetShortcut]
URL=file:///C:\Users\YOUR_USER_NAME\AppData\Local\Programs\Razer\ChromaDiscordApp\ChromaDiscordApp.exe
IconIndex=0
IconFile=C:/Users/YOUR_USER_NAME/AppData/Local/Programs/Razer/ChromaDiscordApp/ChromaDiscordApp.exe
```

Unchecking Launch at Startup deletes the file.

![image](https://user-images.githubusercontent.com/931421/229263442-11e5942a-5ca0-44d8-86a5-ac56a33b316f.png)

**Comment by theAkito** [comment]
May this be closed?
