### ISSUE TITLE
Hide from Alt + Tab

### ISSUE THREAD

**Issue by Erikcb91** [tgraupmann/ChromaDiscordApp#22]
I'd like to know if there is any way to hide the app from showing in alt tab when it's minimized in the system tray, i find it pretty annoying that it's there all the time.
I like the app, but i just want it to run in the background, not to see it every time i Alt + Tab.

Thanks.

**Comment by tgraupmann** [comment]
Good suggestion...

**Comment by Erikcb91** [comment]
is it "easily" doable?
Also, is there a way to change the incoming message color (while keeping the animation) other than just editing it frame by frame and key by key? I only want to make it the same colour as when the app connects to discord (discord "blue") but changing it one by one seems like a lot of work hahahaha
Thanks!

**Comment by tgraupmann** [comment]
After hand painting my N-th fire animation, I created a whole toolset for quickly making animations.

Take a look at the first videos in the guide. You can make some epic animations in a few minutes.

https://chroma.razer.com/ChromaGuide/

**Comment by Erikcb91** [comment]
Awesome, i'll take a look at it. Thanks.
What about the main subject of the issue? is it doable?

**Comment by tgraupmann** [comment]
Yes it's totally doable. I can add it to the backlog. I can't give any sort of ETA for this.

**Comment by Erikcb91** [comment]
It would be great if you do that, i'll stay tuned to see when it's implemented. Thanks!
