### ISSUE TITLE
no way to disable waiting for msg animation

### ISSUE THREAD

**Issue by WHiZSTA** [tgraupmann/ChromaDiscordApp#3]
i'd like my keyboard to notify me of new messages.. the others are fine too... but i dont want it taking over my keyboard 24/7 with a "waiting for message" animation when i have setup my own animations for that. so i'd like to have a way to disable it taking over control of the animations for the waiting for msg.

**Comment by tgraupmann** [comment]
I've modified how it works and removed the waiting for message event. Now when no animations are playing it will fallback to your other apps that have Chroma focus or to Synapse.
