### ISSUE TITLE
Infinite Authorization Loop

### ISSUE THREAD

**Issue by Zer0SumGame** [tgraupmann/ChromaDiscordApp#5]
Title really says it all. Discord was already installed, natch, and I downloaded the Chroma app, checked the "Connect to Discord Events" box, hit "Authorize" on Discord, and then kept hitting it as it kept asking for authorization over and over again.

No error messages, no crashes, just keeps asking. I've attached two screenshots, one each of the SDK window and the Discord Authorization dialog, for what its worth. Turning on Dev Mode doesn't help either.
![screenshot 710](https://user-images.githubusercontent.com/31462848/51540379-ab216e80-1e2c-11e9-810d-1817d315900c.jpg)

![screenshot 709](https://user-images.githubusercontent.com/31462848/51540340-8fb66380-1e2c-11e9-93e9-d12566ad11a9.jpg)

**Comment by acegoal07** [comment]
i am getting that aswell

**Comment by ImDqqn** [comment]
Me2 it's sooooo anoying!
