### ISSUE TITLE
Discord Error occurred forever

### ISSUE THREAD

**Issue by SkyTMW** [tgraupmann/ChromaDiscordApp#6]
every time i press authorize, my keyboard and mouse slowly turn red and it will ask me to authorize multiple times. there are no troubleshooting pages to help why I'm getting errors at all. not really sure what to do right now.

**Comment by Baconbomb** [comment]
Same issue for me. It dont register that i approve the authorization

**Comment by wasdennlos** [comment]
Same exact issue. The second I check the Connect to Discord checkbox it just keeps asking for permissions inside discord and then showing the error animation/lighting after granting them.

**Comment by popcicle2003** [comment]
Same issue here. Hope this gets updated because its an amazing app.

**Comment by OneEyeWillie** [comment]
Same Issue here... Is this App dead?

**Comment by SyntheticVirusZ** [comment]
Same... And the app hasn't been updated in over a year so I'm fearing it's dead.

**Comment by tgraupmann** [comment]
This was tied to the scope issue and has been fixed.
