### ISSUE TITLE
Authorize loop

### ISSUE THREAD

**Issue by StephanBruh** [tgraupmann/ChromaDiscordApp#7]
When I check "Connect to Discord Events" discord keeps asking for authorization every 5s after clicking authorize. 

edit: keyboard flashes red when authorize is clicked

**Comment by lewiswal47** [comment]
Bump. Same issue with me. Im using the Razer Cynosa, App version 1.0.7 and using latest discord version

**Comment by MeedicBear** [comment]
Bump same issue

**Comment by norawibb** [comment]
Same issue

**Comment by kogeki** [comment]
Same issue

**Comment by ldmpub** [comment]
App installed right now ... same authorization loop when checking "Connect to Discord Events".

App uninstalled. Waiting for a fix or a new version if any 🥇.

**Comment by linnjah** [comment]
Same issue here.

**Comment by marrobHD** [comment]
Same issue

**Comment by bigz3y** [comment]
same here rip

**Comment by Wydram** [comment]
Same issue, Any info about fix?

**Comment by MeedicBear** [comment]
I guess it's abandoned unfortunately

**Comment by FearNaBoinne** [comment]
I am seeing the exact same issue, and I do not think it is abandoned per sé, as there were commits only a few days ago...
Maybe he just doesn't look at these issues because he thinks it's perfect?  😛

**Comment by Flimsy-Fox** [comment]
Accoording to https://insider.razer.com/index.php?threads/discord-chroma.30948/ ,
Razer has designated someone to work on it. I'm not sure if the guy that was designated by Razer is the guy developing on this project.

**Comment by b4cktr4ck2** [comment]
Same issue here. Any updates?

**Comment by tgraupmann** [comment]
This is the RPC scope issue again fixed in a previous version.
